### ISSUE TITLE
현우님

### ISSUE THREAD

**Issue by Seojunhwan** [aquamagic9/cub3D#1]
지켜보고 있습니다. 저는 무엇을 하면 될까요?

**Comment by aquamagic9** [comment]
> 지켜보고 있습니다. 저는 무엇을 하면 될까요?

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
지켜보고 계셨다니..,,  열심히 하고 있슴다ㅎㅎ
도와주실건 파싱 조금?? 아직 파싱쪽 예외처리를 못봐서 그쪽 조금 도와주심 감사하죠ㅎㅎ
